name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows:
    name: Windows ${{ matrix.config }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release, RelWithDebInfo]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DIMGUI_WITH_BACKEND=ON -DIMGUI_BACKEND_DX9=ON -DIMGUI_BACKEND_DX11=ON

      - name: Build Library
        run: cmake --build build --config ${{ matrix.config }}

      - name: Install Library
        run: cmake --install build --config ${{ matrix.config }}

      - name: Build Examples (DX9)
        working-directory: examples
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build build --config ${{ matrix.config }} --target win32_dx9

      - name: Build Examples (DX11)
        working-directory: examples
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build build --config ${{ matrix.config }} --target win32_dx11
